// Unit tests for the unified loadtest.config.json schema (loadtest/DESIGN.md
// §2). Every negative test asserts on the named error code from DESIGN
// §2.1's cross-field validation table so a code can never silently drift
// from its test. Uses a FIXTURE copy of summary.json via deriveDevnet's
// override options — never the live tests/devnet/summary.json.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { deriveDevnetConfig } from './deriveDevnet';
import {
  checkOperationalConstraints,
  parseLoadtestConfig,
  serializeLoadtestConfig
} from './schema';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(__dirname, '__fixtures__');
const TESTNET_EXAMPLE_PATH = path.join(__dirname, 'examples/testnet.loadtest.json');

const buildRawDevnetExample = (): unknown =>
  deriveDevnetConfig({
    repoRoot: '/unused-repo-root-for-tests',
    summaryPath: path.join(FIXTURES_DIR, 'summary.json'),
    ciConfigPath: path.join(FIXTURES_DIR, 'config.ci.devnet.json'),
    env: {}
  }).config;

const readTestnetExample = (): unknown => JSON.parse(fs.readFileSync(TESTNET_EXAMPLE_PATH, 'utf8'));

// Deep-cloned, already-schema-valid devnet config for negative tests to
// mutate freely without cross-test interference.
const validDevnetDoc = (): Record<string, unknown> =>
  JSON.parse(JSON.stringify(buildRawDevnetExample())) as Record<string, unknown>;

describe('loadtestConfigSchema — round trip (DESIGN §2 operational definition)', () => {
  // schema.parse(JSON.parse(serialize(schema.parse(JSON.parse(read(X)))))) deepEquals
  // schema.parse(JSON.parse(read(X))), serialize = JSON.stringify(value, null, 2).
  it('round-trips the devnet worked example (generated by derive-devnet)', () => {
    const first = parseLoadtestConfig(buildRawDevnetExample());
    const reparsed = parseLoadtestConfig(JSON.parse(serializeLoadtestConfig(first)));
    expect(reparsed).toStrictEqual(first);
  });

  it('round-trips the testnet worked example (config/examples/testnet.loadtest.json)', () => {
    const first = parseLoadtestConfig(readTestnetExample());
    const reparsed = parseLoadtestConfig(JSON.parse(serializeLoadtestConfig(first)));
    expect(reparsed).toStrictEqual(first);
  });
});

describe('loadtestConfigSchema — happy path examples', () => {
  it('accepts the devnet worked example', () => {
    expect(() => parseLoadtestConfig(buildRawDevnetExample())).not.toThrow();
  });

  it('accepts the testnet worked example, a 2-chain / 2-hop ring with Bokuto networkId 37 (finding C11)', () => {
    const config = parseLoadtestConfig(readTestnetExample());
    expect(config.chains).toHaveLength(2);
    expect(config.ring).toStrictEqual(['SEPOLIA', 'BOKUTO', 'SEPOLIA']);
    expect(config.chains.find((chain) => chain.key === 'BOKUTO')?.networkId).toBe(37);
  });
});

describe('loadtestConfigSchema — cross-field negatives (DESIGN §2.1)', () => {
  it('RING_NOT_CLOSED: ring[0] !== ring[last]', () => {
    const doc = validDevnetDoc();
    (doc.ring as string[])[(doc.ring as string[]).length - 1] = 'L2B';
    expect(() => parseLoadtestConfig(doc)).toThrow(/RING_NOT_CLOSED/);
  });

  it('RING_TOO_SHORT: fewer than 3 ring entries', () => {
    const doc = validDevnetDoc();
    doc.ring = ['L1', 'L1'];
    expect(() => parseLoadtestConfig(doc)).toThrow(/RING_TOO_SHORT/);
  });

  it('RING_TOO_SHORT: a self-loop between consecutive ring entries', () => {
    const doc = validDevnetDoc();
    doc.ring = ['L1', 'L1', 'L2A', 'L1'];
    expect(() => parseLoadtestConfig(doc)).toThrow(/RING_TOO_SHORT/);
  });

  it('RING_UNKNOWN_CHAIN: a ring entry not present in chains', () => {
    const doc = validDevnetDoc();
    doc.ring = ['L1', 'L2A', 'L2C', 'L1'];
    expect(() => parseLoadtestConfig(doc)).toThrow(/RING_UNKNOWN_CHAIN/);
  });

  it('CHAIN_ID_DUPLICATE: duplicate networkId', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[1].networkId = 0;
    expect(() => parseLoadtestConfig(doc)).toThrow(/CHAIN_ID_DUPLICATE/);
  });

  it('CHAIN_ID_DUPLICATE: duplicate chainId', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[1].chainId = (
      doc.chains as Array<Record<string, unknown>>
    )[0].chainId;
    expect(() => parseLoadtestConfig(doc)).toThrow(/CHAIN_ID_DUPLICATE/);
  });

  it('L1_CHAIN_AMBIGUOUS: zero chains with networkId 0', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[0].networkId = 5;
    expect(() => parseLoadtestConfig(doc)).toThrow(/L1_CHAIN_AMBIGUOUS/);
  });

  it('L1_CHAIN_AMBIGUOUS: more than one chain with networkId 0', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[1].networkId = 0;
    // also fix CHAIN_ID_DUPLICATE side effect by keeping chainId distinct — it already is.
    expect(() => parseLoadtestConfig(doc)).toThrow(/L1_CHAIN_AMBIGUOUS/);
  });

  it('AUTOCLAIM_HOP_MISSING: autoclaim map missing a ring hop', () => {
    const doc = validDevnetDoc();
    delete (doc.autoclaim as Record<string, unknown>)['L2B->L1'];
    expect(() => parseLoadtestConfig(doc)).toThrow(/AUTOCLAIM_HOP_MISSING/);
  });

  it('AUTOCLAIM_HOP_UNKNOWN: autoclaim entry not a ring hop', () => {
    const doc = validDevnetDoc();
    (doc.autoclaim as Record<string, unknown>)['L2B->L2A'] = { expected: false };
    expect(() => parseLoadtestConfig(doc)).toThrow(/AUTOCLAIM_HOP_UNKNOWN/);
  });

  it('AUTOCLAIM_WAIT_REQUIRED: expected true without waitMs', () => {
    const doc = validDevnetDoc();
    (doc.autoclaim as Record<string, unknown>)['L1->L2A'] = { expected: true };
    expect(() => parseLoadtestConfig(doc)).toThrow(/AUTOCLAIM_WAIT_REQUIRED/);
  });

  it('UI_BASE_URL_REQUIRED: users.browser > 0 without uiBaseUrl', () => {
    const doc = validDevnetDoc();
    delete doc.uiBaseUrl;
    expect(() => parseLoadtestConfig(doc)).toThrow(/UI_BASE_URL_REQUIRED/);
  });

  it('DEVNET_FUNDING_NOT_ALLOWED: devnetFunding set on a non-devnet env', () => {
    const doc = validDevnetDoc();
    doc.env = 'testnet';
    // testnet requires uiBaseUrl too (already present) and a real ring/asset
    // shape isn't relevant to this check — devnetFunding is env-gated
    // independently of everything else.
    expect(() => parseLoadtestConfig(doc)).toThrow(/DEVNET_FUNDING_NOT_ALLOWED/);
  });

  it('FUNDER_REQUIRED: funder omitted when env is not devnet+anvil_setBalance', () => {
    const doc = validDevnetDoc();
    doc.env = 'testnet';
    delete (doc.users as Record<string, unknown>).devnetFunding;
    delete (doc.users as Record<string, unknown>).funder;
    expect(() => parseLoadtestConfig(doc)).toThrow(/FUNDER_REQUIRED/);
  });

  it('INLINE_PRIVATE_KEY_FORBIDDEN: a 32-byte hex literal anywhere in the document', () => {
    // The top-level object is `.strict()`, so the literal has to land in an
    // EXISTING free-form string field (explorerUrl has no format
    // constraint of its own) rather than an ad-hoc extra key, which strict
    // mode would reject before the inline-key scan ever ran.
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[0].explorerUrl =
      '0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625';
    expect(() => parseLoadtestConfig(doc)).toThrow(/INLINE_PRIVATE_KEY_FORBIDDEN/);
  });

  it('INLINE_PRIVATE_KEY_FORBIDDEN: rejects a key mistakenly placed in a secretRef env-name slot', () => {
    // A secretRef's `env` field is just a free-form env-var-NAME string
    // structurally (any non-empty string), so this stays structurally valid
    // and reaches the recursive inline-key scan — unlike putting the literal
    // somewhere with its own incompatible format constraint (e.g.
    // `address`), which would fail structural parsing first and never reach
    // this check at all.
    const doc = validDevnetDoc();
    (doc.users as { funder: Record<string, unknown> }).funder.privateKeyRef = {
      env: '0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625'
    };
    expect(() => parseLoadtestConfig(doc)).toThrow(/INLINE_PRIVATE_KEY_FORBIDDEN/);
  });

  // S12 hardening pass — the remaining cross-field negatives below had
  // production code (schema.ts) but no test anywhere before this.

  it('CHAIN_KEY_DUPLICATE: two chains share the same .key', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[1].key = (
      doc.chains as Array<Record<string, unknown>>
    )[0].key;
    expect(() => parseLoadtestConfig(doc)).toThrow(/CHAIN_KEY_DUPLICATE/);
  });

  it('FUNDER_GAS_PER_CHAIN_MISSING: funder.gasPerChain is missing an entry for a ring chain', () => {
    const doc = validDevnetDoc();
    delete (doc.users as { funder: { gasPerChain: Record<string, unknown> } }).funder.gasPerChain
      .L2A;
    expect(() => parseLoadtestConfig(doc)).toThrow(/FUNDER_GAS_PER_CHAIN_MISSING/);
  });

  it('FUNDER_MAX_TOTAL_SPEND_MISSING: funder.maxTotalSpend is missing an entry for a ring chain', () => {
    const doc = validDevnetDoc();
    delete (doc.users as { funder: { maxTotalSpend: Record<string, unknown> } }).funder
      .maxTotalSpend.L2A;
    expect(() => parseLoadtestConfig(doc)).toThrow(/FUNDER_MAX_TOTAL_SPEND_MISSING/);
  });

  it('ASSET_ETH_DUPLICATE: more than one asset with kind "eth"', () => {
    const doc = validDevnetDoc();
    const assets = doc.assets as Array<Record<string, unknown>>;
    assets.push({ ...assets[0] });
    expect(() => parseLoadtestConfig(doc)).toThrow(/ASSET_ETH_DUPLICATE/);
  });

  it('ASSET_ERC20_ADDRESS_DUPLICATE: two erc20 assets share the same address (case-insensitively)', () => {
    const doc = validDevnetDoc();
    const assets = doc.assets as Array<Record<string, unknown>>;
    const erc20 = assets.find((asset) => asset.kind === 'erc20') as Record<string, unknown>;
    assets.push({ ...erc20, address: String(erc20.address).toUpperCase() });
    expect(() => parseLoadtestConfig(doc)).toThrow(/ASSET_ERC20_ADDRESS_DUPLICATE/);
  });

  it("ASSET_ORIGIN_NETWORK_UNKNOWN: an erc20 asset's originNetworkId matches no chain", () => {
    const doc = validDevnetDoc();
    const assets = doc.assets as Array<Record<string, unknown>>;
    const erc20 = assets.find((asset) => asset.kind === 'erc20') as Record<string, unknown>;
    erc20.originNetworkId = 999;
    expect(() => parseLoadtestConfig(doc)).toThrow(/ASSET_ORIGIN_NETWORK_UNKNOWN/);
  });

  it('AGGKIT_PROXY_URL_TRAILING_SLASH: aggkitProxyUrl ends with "/"', () => {
    const doc = validDevnetDoc();
    doc.aggkitProxyUrl = `${doc.aggkitProxyUrl}/`;
    expect(() => parseLoadtestConfig(doc)).toThrow(/AGGKIT_PROXY_URL_TRAILING_SLASH/);
  });

  it('AGGKIT_PROXY_URL_SUFFIX_FORBIDDEN: aggkitProxyUrl ends with /bridge/v1 or /tracker/v1', () => {
    const doc = validDevnetDoc();
    doc.aggkitProxyUrl = `${doc.aggkitProxyUrl}/bridge/v1`;
    expect(() => parseLoadtestConfig(doc)).toThrow(/AGGKIT_PROXY_URL_SUFFIX_FORBIDDEN/);
  });

  // R19 (loadtest/REVIEW.md, added S21): `maxTotalSpend` capped native
  // currency only — an erc20 top-up on a non-devnet-anvil fund had NO cap
  // of any kind. `FUNDER_MAX_ERC20_SPEND_REQUIRED` closes that.
  it('FUNDER_MAX_ERC20_SPEND_REQUIRED: erc20 asset + a funder required (non-devnet-anvil) with no cap set', () => {
    const doc = validDevnetDoc();
    doc.env = 'testnet';
    delete (doc.users as Record<string, unknown>).devnetFunding;
    expect(() => parseLoadtestConfig(doc)).toThrow(/FUNDER_MAX_ERC20_SPEND_REQUIRED/);
  });

  it('accepts an erc20 asset on a non-devnet-anvil fund once maxTotalErc20Spend is set', () => {
    const doc = validDevnetDoc();
    doc.env = 'testnet';
    delete (doc.users as Record<string, unknown>).devnetFunding;
    (doc.users as { funder: Record<string, unknown> }).funder.maxTotalErc20Spend = '1000';
    expect(() => parseLoadtestConfig(doc)).not.toThrow();
  });

  it('does NOT require maxTotalErc20Spend on the devnet anvil_setBalance path (no real-funds risk)', () => {
    const doc = validDevnetDoc();
    expect(() => parseLoadtestConfig(doc)).not.toThrow();
    expect(
      (doc.users as { funder: Record<string, unknown> }).funder.maxTotalErc20Spend
    ).toBeUndefined();
  });

  // R23 (loadtest/REVIEW.md, added S21): nothing previously cross-checked
  // the `env` label against the actual chains.
  it('ENV_RPC_URL_MISMATCH: env "devnet" but a chain rpcUrl is not loopback', () => {
    const doc = validDevnetDoc();
    (doc.chains as Array<Record<string, unknown>>)[0].rpcUrl =
      'https://ethereum-sepolia-rpc.publicnode.com';
    expect(() => parseLoadtestConfig(doc)).toThrow(/ENV_RPC_URL_MISMATCH/);
  });

  it('ENV_CHAIN_ID_MISMATCH: env "mainnet" but the L1 chain is not chainId 1', () => {
    const doc = validDevnetDoc();
    doc.env = 'mainnet';
    delete (doc.users as Record<string, unknown>).devnetFunding;
    (doc.users as { funder: Record<string, unknown> }).funder.maxTotalErc20Spend = '1000';
    expect(() => parseLoadtestConfig(doc)).toThrow(/ENV_CHAIN_ID_MISMATCH/);
  });

  it('ENV_CHAIN_ID_MISMATCH: the L1 chain is chainId 1 (Ethereum mainnet) but env is not "mainnet"', () => {
    const doc = validDevnetDoc();
    const l1 = (doc.chains as Array<Record<string, unknown>>).find(
      (chain) => chain.networkId === 0
    )!;
    l1.chainId = 1;
    expect(() => parseLoadtestConfig(doc)).toThrow(/ENV_CHAIN_ID_MISMATCH/);
  });

  // R9 (loadtest/REVIEW.md, added S21): with no guard, `--minutes 1` at the
  // default 60s ramp reported an achieved rate of exactly 0.0000 with no
  // warning anywhere.
  it('RAMP_UP_EXCEEDS_DURATION: rampUpSeconds >= durationMinutes * 60', () => {
    const doc = validDevnetDoc();
    (doc.load as Record<string, unknown>).durationMinutes = 1;
    (doc.load as Record<string, unknown>).rampUpSeconds = 60;
    expect(() => parseLoadtestConfig(doc)).toThrow(/RAMP_UP_EXCEEDS_DURATION/);
  });

  it('accepts rampUpSeconds strictly less than durationMinutes * 60', () => {
    const doc = validDevnetDoc();
    (doc.load as Record<string, unknown>).durationMinutes = 2;
    (doc.load as Record<string, unknown>).rampUpSeconds = 60;
    expect(() => parseLoadtestConfig(doc)).not.toThrow();
  });
});

describe('checkOperationalConstraints — validate-only checks (DESIGN §2.4, §3.7)', () => {
  it('PROXY_URL_PLACEHOLDER: rejects a placeholder aggkitProxyUrl host', () => {
    const config = parseLoadtestConfig(readTestnetExample());
    const issues = checkOperationalConstraints(config);
    expect(issues.some((issue) => issue.startsWith('PROXY_URL_PLACEHOLDER'))).toBe(true);
  });

  it('PROXY_URL_PLACEHOLDER: also rejects the literal PLACEHOLDER host from config.json', () => {
    const doc = validDevnetDoc();
    doc.aggkitProxyUrl = 'https://PLACEHOLDER-testnet-aggkit-proxy';
    const config = parseLoadtestConfig(doc);
    const issues = checkOperationalConstraints(config);
    expect(issues.some((issue) => issue.startsWith('PROXY_URL_PLACEHOLDER'))).toBe(true);
  });

  it('does not flag a real aggkitProxyUrl host', () => {
    const config = parseLoadtestConfig(buildRawDevnetExample());
    const issues = checkOperationalConstraints(config);
    expect(issues.some((issue) => issue.startsWith('PROXY_URL_PLACEHOLDER'))).toBe(false);
  });

  it('RING_MUST_START_AT_ASSET_ORIGIN: ring[0] is not the erc20 asset origin chain (DESIGN §3.7)', () => {
    const doc = validDevnetDoc();
    doc.ring = ['L2A', 'L2B', 'L1', 'L2A'];
    doc.autoclaim = {
      'L2A->L2B': { expected: true, waitMs: 300_000 },
      'L2B->L1': { expected: false },
      'L1->L2A': { expected: true, waitMs: 120_000 }
    };
    const config = parseLoadtestConfig(doc);
    const issues = checkOperationalConstraints(config);
    expect(issues.some((issue) => issue.startsWith('RING_MUST_START_AT_ASSET_ORIGIN'))).toBe(true);
  });

  it('does not flag a ring whose first hop originates at the erc20 asset origin chain', () => {
    const config = parseLoadtestConfig(buildRawDevnetExample());
    const issues = checkOperationalConstraints(config);
    expect(issues.some((issue) => issue.startsWith('RING_MUST_START_AT_ASSET_ORIGIN'))).toBe(false);
  });
});
